name: cea
channels:
  - defaults
  - conda-forge
  - pythonocc
  - oce
  - dlr-sc
  - r
  - udst
dependencies:
  - geopandas
  - numba>=0.42.0
  - python>=3.7
  - osmnx
  - psutil
  - pythonocc-core
  - pysal=2.1.0
  - libiconv
  - pandana
  - urbanaccess

